### ISSUE TITLE
Fails to test the project

### ISSUE THREAD

**Issue by taringamberini** [fpinjava/fpinjava#4]
I'm using jdk version 1.8.0_25 but running:

    $ gradle clean test

I get the error:

    :clean UP-TO-DATE
    :fpinjava-common:clean
    :fpinjava-datastructures-exercises:clean UP-TO-DATE
    :fpinjava-datastructures-solutions:clean UP-TO-DATE
    :fpinjava-errorhandling-exercises:clean UP-TO-DATE
    :fpinjava-errorhandling-solutions:clean UP-TO-DATE
    :fpinjava-functionalparallelism-exercises:clean UP-TO-DATE
    :fpinjava-functionalparallelism-solutions:clean UP-TO-DATE
    :fpinjava-functionalstate-exercises:clean UP-TO-DATE
    :fpinjava-functionalstate-solutions:clean UP-TO-DATE
    :fpinjava-introduction:clean UP-TO-DATE
    :fpinjava-laziness-exercises:clean UP-TO-DATE
    :fpinjava-laziness-solutions:clean UP-TO-DATE
    :fpinjava-makingjavafunctional-exercises:clean UP-TO-DATE
    :fpinjava-makingjavafunctional-solutions:clean UP-TO-DATE
    :fpinjava-propertybasedtesting-exercises:clean UP-TO-DATE
    :fpinjava-propertybasedtesting-solutions:clean UP-TO-DATE
    :fpinjava-recursion-exercises:clean UP-TO-DATE
    :fpinjava-recursion-solutions:clean UP-TO-DATE
    :fpinjava-test:clean UP-TO-DATE
    :fpinjava-usingfunctions-exercises:clean UP-TO-DATE
    :fpinjava-usingfunctions-solutions:clean UP-TO-DATE
    :compileJava UP-TO-DATE
    :processResources UP-TO-DATE
    :classes UP-TO-DATE
    :compileTestJava UP-TO-DATE
    :processTestResources UP-TO-DATE
    :testClasses UP-TO-DATE
    :test UP-TO-DATE
    :fpinjava-common:compileJava
    An exception has occurred in the compiler (1.8.0_25). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
    java.lang.NullPointerException
	    at com.sun.tools.javac.code.Types.isConvertible(Types.java:290)
	    at com.sun.tools.javac.comp.Check.assertConvertible(Check.java:922)
	    at com.sun.tools.javac.comp.Check.checkMethod(Check.java:876)
	    at com.sun.tools.javac.comp.Attr.checkMethod(Attr.java:3838)
	    at com.sun.tools.javac.comp.Attr.checkIdInternal(Attr.java:3615)
	    at com.sun.tools.javac.comp.Attr.checkMethodIdInternal(Attr.java:3522)
	    at com.sun.tools.javac.comp.Attr.checkMethodId(Attr.java:3501)
	    at com.sun.tools.javac.comp.Attr.checkId(Attr.java:3488)
	    at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3370)
	    at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
	    at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607)
	    at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1843)
	    at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
	    at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607)
	    at com.sun.tools.javac.comp.Attr.visitReturn(Attr.java:1704)
	    at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1384)
	    at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607)
	    at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:676)
	    at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:692)
	    at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1142)
	    at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	    at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607)
	    at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:676)
	    at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1035)
	    at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
	    at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607)
	    at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:676)
	    at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4342)
	    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4252)
	    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4181)
	    at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4156)
	    at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248)
	    at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
	    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
	    at com.sun.tools.javac.main.Main.compile(Main.java:523)
	    at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	    at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:42)
	    at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
	    at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:97)
	    at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
	    at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
	    at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
	    at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	    at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:156)
	    at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:136)
	    at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:90)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:483)
	    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:235)
	    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:222)
	    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	    at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:306)
	    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	    at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	    at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	    at org.gradle.launcher.Main.doAction(Main.java:33)
	    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:483)
	    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    :fpinjava-common:compileJava FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':fpinjava-common:compileJava'.
    > Compilation failed; see the compiler error output for details.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 4.421 secs

**Comment by taringamberini** [comment]
I've found a similar error on https://bugs.openjdk.java.net/browse/JDK-8062253 and it seems an error of the jdk fixed in jdk 1.8.0_40.

So I've installed the jdk 1.8.0_40, the last jdk available at the moment, and running again:

    $ gradle clean test

the error is disapeared:

    :clean UP-TO-DATE
    :fpinjava-common:clean
    :fpinjava-datastructures-exercises:clean UP-TO-DATE
    :fpinjava-datastructures-solutions:clean UP-TO-DATE
    :fpinjava-errorhandling-exercises:clean UP-TO-DATE
    :fpinjava-errorhandling-solutions:clean UP-TO-DATE
    :fpinjava-functionalparallelism-exercises:clean UP-TO-DATE
    :fpinjava-functionalparallelism-solutions:clean UP-TO-DATE
    :fpinjava-functionalstate-exercises:clean UP-TO-DATE
    :fpinjava-functionalstate-solutions:clean UP-TO-DATE
    :fpinjava-introduction:clean
    :fpinjava-laziness-exercises:clean UP-TO-DATE
    :fpinjava-laziness-solutions:clean UP-TO-DATE
    :fpinjava-makingjavafunctional-exercises:clean UP-TO-DATE
    :fpinjava-makingjavafunctional-solutions:clean UP-TO-DATE
    :fpinjava-propertybasedtesting-exercises:clean UP-TO-DATE
    :fpinjava-propertybasedtesting-solutions:clean UP-TO-DATE
    :fpinjava-recursion-exercises:clean
    :fpinjava-recursion-solutions:clean
    :fpinjava-test:clean UP-TO-DATE
    :fpinjava-usingfunctions-exercises:clean UP-TO-DATE
    :fpinjava-usingfunctions-solutions:clean UP-TO-DATE
    :compileJava UP-TO-DATE
    :processResources UP-TO-DATE
    :classes UP-TO-DATE
    :compileTestJava UP-TO-DATE
    :processTestResources UP-TO-DATE
    :testClasses UP-TO-DATE
    :test UP-TO-DATE
    :fpinjava-common:compileJava
    :fpinjava-common:processResources UP-TO-DATE
    :fpinjava-common:classes
    :fpinjava-common:compileTestJava UP-TO-DATE
    :fpinjava-common:processTestResources UP-TO-DATE
    :fpinjava-common:testClasses UP-TO-DATE
    :fpinjava-common:test UP-TO-DATE
    :fpinjava-common:jar
    :fpinjava-datastructures-exercises:compileJava
    :fpinjava-datastructures-exercises:processResources UP-TO-DATE
    :fpinjava-datastructures-exercises:classes
    :fpinjava-datastructures-exercises:compileTestJava
    :fpinjava-datastructures-exercises:processTestResources UP-TO-DATE
    :fpinjava-datastructures-exercises:testClasses
    :fpinjava-datastructures-exercises:test

    com.fpinjava.datastructures.exercise05_27.ListTest > testHasSubsequence FAILED
        java.lang.IllegalStateException at ListTest.java:11
    ...

the exeception are correctly thrown by exercises not yet completed: see the section [Doing the exercises](https://github.com/fpinjava/fpinjava#user-content-doing-the-exercises).

It isn't a problem of the source code but its due to my old jdk installation: I've reported it only for documenting purpose.

This issue can be closed.

**Comment by pysaumont** [comment]
I found many similar problem with various versions of the JDK 8, including 1.8.0_40. However, I could not make a minimal project showing the error, because while removing code that seemed to be non related, the errors disappeared. So I could not submit a bug report.

Closing the issue.
